### ISSUE TITLE
Cut a 2.0 release

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/winchecksec#37]
There hasn't been a stable winchecksec release in over a year, meaning that we haven't stabilized the pe-parse integration and other improvements made in that period.

Here's the release needlist:

- [ ] Enable tests in the CI (#47)
- [x] Enforce code style with `clang-format` in the CI (#50)
- [ ] Move `VERSION` to `Checksec.cpp`, to emphasize that we're versioning the entire project and not just the CLI interface
- [ ] Actually bump `VERSION` in `main.cpp`
- [ ] Use smolverify to verify Authenticode signatures on Linux (#39)
- [ ] Publish build products for releases (via a GitHub action, see pegoat)

Wantlist:
- [x] Builds for Linux and macOS (#38, #51)

cc @ekilmer

**Comment by ekilmer** [comment]
We should add a code formatter recommendation/enforcement

**Comment by woodruffw** [comment]
> We should add a code formatter recommendation/enforcement

Definitely! Added to the needlist above.

**Comment by woodruffw** [comment]
Turning this into a milestone.
